version: "3"

services:
  mysql:
    image: mysql/mysql-server:5.7
    restart: always
    ports:
      - 3340:3306
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=1
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWD}
      - MYSQL_DATABASE=${DB_NAME}

  prestashop_1.6.1:
    image: prestashop/prestashop:1.6
    depends_on:
      - mysql
    ports:
      - 8016:80
    volumes:
      - .:/var/www/html/modules/senderautomatedemails
    environment:
      - DB_SERVER=mysql
      - DB_PREFIX=ps161_
      - PS_DEV_MODE=${PS_DEV_MODE}
      - PS_INSTALL_AUTO=1
      - DB_USER=${DB_USER}
      - DB_PASSWD=${DB_PASSWD}
      - DB_NAME=${DB_NAME}
      - PS_FOLDER_ADMIN=${PS_FOLDER_ADMIN}
      - PS_DOMAIN=${PS_DOMAIN}:8016
      - PS_LANGUAGE=${PS_LANGUAGE}
      - PS_COUNTRY=${PS_COUNTRY}
      - PS_FOLDER_INSTALL=installed
      - ADMIN_MAIL=${PS_ADMIN_MAIL}
      - ADMIN_PASSWD=${PS_ADMIN_PASSWD}

  prestashop_1.7.1:
    image: prestashop/prestashop:1.7.1.0
    depends_on:
      - mysql
    ports:
      - 8171:80
    volumes:
      - .:/var/www/html/modules/senderautomatedemails
    environment:
      - DB_SERVER=mysql
      - DB_PREFIX=ps171_
      - PS_DEV_MODE=${PS_DEV_MODE}
      - PS_INSTALL_AUTO=1
      - DB_USER=${DB_USER}
      - DB_PASSWD=${DB_PASSWD}
      - DB_NAME=${DB_NAME}
      - PS_FOLDER_ADMIN=${PS_FOLDER_ADMIN}
      - PS_DOMAIN=${PS_DOMAIN}:8171
      - PS_LANGUAGE=${PS_LANGUAGE}
      - PS_COUNTRY=${PS_COUNTRY}
      - PS_FOLDER_INSTALL=installed
      - ADMIN_MAIL=${PS_ADMIN_MAIL}
      - ADMIN_PASSWD=${PS_ADMIN_PASSWD}

  prestashop_1.7.2:
    image: prestashop/prestashop:1.7.2.4
    depends_on:
      - mysql
    ports:
      - 8172:80
    volumes:
      - .:/var/www/html/modules/senderautomatedemails
    environment:
      - DB_SERVER=mysql
      - DB_PREFIX=ps172_
      - PS_DEV_MODE=${PS_DEV_MODE}
      - PS_INSTALL_AUTO=1
      - DB_USER=${DB_USER}
      - DB_PASSWD=${DB_PASSWD}
      - DB_NAME=${DB_NAME}
      - PS_FOLDER_ADMIN=${PS_FOLDER_ADMIN}
      - PS_DOMAIN=${PS_DOMAIN}:8172
      - PS_LANGUAGE=${PS_LANGUAGE}
      - PS_COUNTRY=${PS_COUNTRY}
      - PS_FOLDER_INSTALL=installed
      - ADMIN_MAIL=${PS_ADMIN_MAIL}
      - ADMIN_PASSWD=${PS_ADMIN_PASSWD}

  prestashop_1.7.3:
    image: prestashop/prestashop:1.7.3
    depends_on:
      - mysql
    ports:
      - 8173:80
    volumes:
      - .:/var/www/html/modules/senderautomatedemails
    environment:
      - DB_SERVER=mysql
      - DB_PREFIX=ps173_
      - PS_DEV_MODE=${PS_DEV_MODE}
      - PS_INSTALL_AUTO=1
      - DB_USER=${DB_USER}
      - DB_PASSWD=${DB_PASSWD}
      - DB_NAME=${DB_NAME}
      - PS_FOLDER_ADMIN=${PS_FOLDER_ADMIN}
      - PS_DOMAIN=${PS_DOMAIN}:8173
      - PS_LANGUAGE=${PS_LANGUAGE}
      - PS_COUNTRY=${PS_COUNTRY}
      - PS_FOLDER_INSTALL=installed
      - ADMIN_MAIL=${PS_ADMIN_MAIL}
      - ADMIN_PASSWD=${PS_ADMIN_PASSWD}
